name: AI Agent Workflow

on:
  issues:
    types: [assigned]
  pull_request:
    types: [review_requested]
  workflow_dispatch:  # Allow manual triggering for testing

env:
  ANTHROPIC_BASE_URL: ${{ secrets.CUSTOM_ANTHROPIC_BASE_URL }}
  ANTHROPIC_API_KEY: ${{ secrets.CUSTOM_ANTHROPIC_TOKEN }}
  CLAUDE_CODE_CONFIG_DIR: ${{ github.workspace }}/.claude-agents

jobs:
  ai-agent-task:
    name: AI Agent Task Handler
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Prevent self-triggering, but allow manual runs for testing
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.actor != 'claude[bot]' && (
        (github.event.issue && github.event.issue.assignee.login == 'enacton-ai') ||
        (github.event.pull_request && contains(github.event.pull_request.requested_reviewers.*.login, 'enacton-ai'))
      ))

    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect tech stack
        id: detect-stack
        run: |
          STACK=""

          # Check for Laravel
          if [ -f "composer.json" ]; then
            STACK="$STACK,laravel"
            echo "✓ Detected: Laravel"
          fi

          # Check for Next.js
          if [ -f "next.config.js" ] || [ -f "next.config.mjs" ] || [ -f "next.config.ts" ]; then
            STACK="$STACK,nextjs"
            echo "✓ Detected: Next.js"
          fi

          # Check for React Native
          if [ -d "android" ] || [ -d "ios" ]; then
            STACK="$STACK,reactnative"
            echo "✓ Detected: React Native"
          fi

          # Check for Expo
          if [ -f "app.json" ] && grep -q "expo" app.json 2>/dev/null; then
            STACK="$STACK,expo"
            echo "✓ Detected: Expo"
          fi

          # Remove leading comma and save to output
          STACK="${STACK#,}"
          echo "stack=$STACK" >> $GITHUB_OUTPUT
          echo "Final stack: $STACK"

      - name: Verify agents exist
        run: |
          echo "Checking for AI agents..."
          if [ -d "$CLAUDE_CODE_CONFIG_DIR/agents" ]; then
            echo "✓ Agents directory found"
            echo "Available agents:"
            find "$CLAUDE_CODE_CONFIG_DIR/agents" -name "*.json" -exec basename {} \; | sed 's/.json$//'
          else
            echo "✗ No agents found! Please run: curl -sSL https://raw.githubusercontent.com/enact-on/ai-agent-config/main/scripts/install.sh | bash"
            exit 1
          fi

      - name: Process Issue (Implementation)
        if: github.event_name == 'issues' || github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ISSUE_NUMBER="0"
            ISSUE_TITLE="Manual Workflow Test"
            ISSUE_BODY="Manual test run from Actions tab"
          else
            ISSUE_NUMBER="${{ github.event.issue.number }}"
            ISSUE_TITLE="${{ github.event.issue.title }}"
            ISSUE_BODY="${{ github.event.issue.body }}"
          fi

          echo "=========================================="
          echo "Processing Issue: #$ISSUE_NUMBER"
          echo "Title: $ISSUE_TITLE"
          echo "Stack: ${{ steps.detect-stack.outputs.stack }}"
          echo "Event: ${{ github.event_name }}"
          echo "=========================================="

          # Note: This is a placeholder for actual AI implementation
          # The actual implementation would call the Anthropic API here
          # For now, this creates a comment to acknowledge the issue

          echo "AI Agent would process this issue."
          echo "This requires Anthropic API integration."

      - name: Process Pull Request (Review)
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"

          echo "=========================================="
          echo "Reviewing PR: #$PR_NUMBER"
          echo "Title: $PR_TITLE"
          echo "Stack: ${{ steps.detect-stack.outputs.stack }}"
          echo "=========================================="

          # Get PR diff
          echo "Fetching PR changes..."
          git fetch origin main
          git diff origin/main...HEAD > /tmp/pr.diff

          echo "Files changed:"
          git diff --name-only origin/main...HEAD

          # Note: This is a placeholder for actual AI review
          # The actual implementation would call the Anthropic API here
          # For now, this posts a placeholder comment

      - name: Post comment on issue
        if: github.event_name == 'issues' && success()
        run: |
          COMMENT="## 🤖 AI Agent Acknowledgment

          **Issue:** #${{ github.event.issue.number }} - ${{ github.event.issue.title }}
          **Tech Stack:** ${{ steps.detect-stack.outputs.stack }}

          ### What Happens Next:
          1. ✅ Tech stack detected: \`${{ steps.detect-stack.outputs.stack }}\`
          2. ✅ AI agents loaded from: \`.claude-agents/\`
          3. ⏳ **Note:** Full AI implementation requires Anthropic API integration

          ### Setup Required:
          - Ensure \`CUSTOM_ANTHROPIC_BASE_URL\` is set in repository secrets
          - Ensure \`CUSTOM_ANTHROPIC_TOKEN\` is set in repository secrets
          - The actual AI processing logic will be implemented in the next phase

          ---
          *Processed by: enacton-ai*"

          gh issue comment "${{ github.event.issue.number }}" --body "$COMMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post comment on PR
        if: github.event_name == 'pull_request'
        run: |
          COMMENT="## 🤖 AI Agent Review

          **PR:** #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
          **Tech Stack:** ${{ steps.detect-stack.outputs.stack }}

          ### Files Changed:
          \`\`\`
          $(git diff --name-only origin/main...HEAD | head -20)
          \`\`\`

          ### What Happens Next:
          1. ✅ Tech stack detected
          2. ✅ PR changes analyzed
          3. ⏳ **Note:** Full AI review requires Anthropic API integration

          ### Setup Required:
          - Ensure secrets are configured
          - AI will review code quality, security, and best practices

          ---
          *Reviewed by: enacton-ai*"

          gh pr comment "${{ github.event.pull_request.number }}" --body "$COMMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unassign AI agent (if issue)
        if: github.event_name == 'issues' && success() && github.event.issue.assignee.login == 'enacton-ai'
        run: |
          echo "Removing AI agent assignment..."
          gh issue edit "${{ github.event.issue.number }}" --remove-assignee "enacton-ai"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
