name: AI Agent Workflow

on:
  issues:
    types: [assigned]
  pull_request:
    types: [review_requested]
  workflow_dispatch:  # Allow manual triggering for testing

env:
  ANTHROPIC_BASE_URL: ${{ secrets.CUSTOM_ANTHROPIC_BASE_URL }}
  ANTHROPIC_API_KEY: ${{ secrets.CUSTOM_ANTHROPIC_TOKEN }}
  CLAUDE_CODE_CONFIG_DIR: ${{ github.workspace }}/.claude-agents

jobs:
  ai-agent-task:
    name: AI Agent Task Handler
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Prevent self-triggering, but allow manual runs for testing
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.actor != 'claude[bot]' && (
        (github.event.issue && github.event.issue.assignee.login == 'enacton-ai') ||
        (github.event.pull_request && contains(github.event.pull_request.requested_reviewers.*.login, 'enacton-ai'))
      ))

    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect tech stack
        id: detect-stack
        run: |
          STACK=""

          # Check for Laravel
          if [ -f "composer.json" ]; then
            STACK="$STACK,laravel"
            echo "✓ Detected: Laravel"
          fi

          # Check for Next.js
          if [ -f "next.config.js" ] || [ -f "next.config.mjs" ] || [ -f "next.config.ts" ]; then
            STACK="$STACK,nextjs"
            echo "✓ Detected: Next.js"
          fi

          # Check for React Native
          if [ -d "android" ] || [ -d "ios" ]; then
            STACK="$STACK,reactnative"
            echo "✓ Detected: React Native"
          fi

          # Check for Expo
          if [ -f "app.json" ] && grep -q "expo" app.json 2>/dev/null; then
            STACK="$STACK,expo"
            echo "✓ Detected: Expo"
          fi

          # Remove leading comma and save to output
          STACK="${STACK#,}"
          echo "stack=$STACK" >> $GITHUB_OUTPUT
          echo "Final stack: $STACK"

      - name: Verify agents exist
        run: |
          echo "Checking for AI agents..."
          if [ -d "$CLAUDE_CODE_CONFIG_DIR/agents" ]; then
            echo "✓ Agents directory found"
            echo "Available agents:"
            find "$CLAUDE_CODE_CONFIG_DIR/agents" -name "*.json" -exec basename {} \; | sed 's/.json$//'
          else
            echo "✗ No agents found! Please run: curl -sSL https://raw.githubusercontent.com/enact-on/ai-agent-config/main/scripts/install.sh | bash"
            exit 1
          fi

      - name: Setup Claude Code CLI
        run: |
          # Install Claude Code CLI if not present
          if ! command -v claude &> /dev/null; then
            echo "Installing Claude Code CLI..."
            npm install -g @anthropic-ai/claude-code
          fi

          # Verify installation
          claude --version

      - name: Process Issue (Implementation)
        if: github.event_name == 'issues' || github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ISSUE_NUMBER="0"
            ISSUE_TITLE="Manual Workflow Test"
            ISSUE_BODY="Manual test run from Actions tab"
          else
            ISSUE_NUMBER="${{ github.event.issue.number }}"
            ISSUE_TITLE="${{ github.event.issue.title }}"
            ISSUE_BODY="${{ github.event.issue.body }}"
          fi

          echo "=========================================="
          echo "Processing Issue: #$ISSUE_NUMBER"
          echo "Title: $ISSUE_TITLE"
          echo "Stack: ${{ steps.detect-stack.outputs.stack }}"
          echo "Event: ${{ github.event_name }}"
          echo "=========================================="

          # Build the prompt for Claude Code
          PROMPT="Issue: $ISSUE_TITLE

          Description:
          $ISSUE_BODY

          Tech Stack: ${{ steps.detect-stack.outputs.stack }}

          Please implement this task according to the agent configurations in .claude-agents/
          Make all necessary file changes and ensure the code follows the repository's patterns.
          After completing the implementation, the changes will be committed automatically."

          # Execute Claude Code with the prompt
          # Claude will read the agent configs from CLAUDE_CODE_CONFIG_DIR
          claude --prompt "$PROMPT" --config-dir "$CLAUDE_CODE_CONFIG_DIR"

      - name: Process Pull Request (Review)
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"

          echo "=========================================="
          echo "Reviewing PR: #$PR_NUMBER"
          echo "Title: $PR_TITLE"
          echo "Stack: ${{ steps.detect-stack.outputs.stack }}"
          echo "=========================================="

          # Get PR diff
          echo "Fetching PR changes..."
          git fetch origin main
          git diff origin/main...HEAD > /tmp/pr.diff

          echo "Files changed:"
          git diff --name-only origin/main...HEAD

          # Build the prompt for Claude Code review
          REVIEW_PROMPT="Pull Request Review: $PR_TITLE

          Please review this PR for:
          - Code quality and best practices
          - Security vulnerabilities
          - Performance considerations
          - Testing coverage
          - Alignment with ${{ steps.detect-stack.outputs.stack }} conventions

          Files changed:
          $(git diff --name-only origin/main...HEAD)

          Diff:
          $(git diff origin/main...HEAD)

          Provide constructive feedback as PR comments."

          # Execute Claude Code for review
          claude --prompt "$REVIEW_PROMPT" --config-dir "$CLAUDE_CODE_CONFIG_DIR"

      - name: Commit and push changes
        if: github.event_name == 'issues' && success()
        run: |
          # Configure git
          git config user.name "enacton-ai"
          git config user.email "enacton-ai@github.com"

          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing..."

            # Get default branch
            DEFAULT_BRANCH=$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)

            # Add all changes
            git add -A

            # Create commit
            git commit -m "Implement: ${{ github.event.issue.title }}

            - Issue: #${{ github.event.issue.number }}
            - Tech Stack: ${{ steps.detect-stack.outputs.stack }}
            - Processed by: enacton-ai"

            # Push to default branch
            git push origin HEAD:$DEFAULT_BRANCH

            echo "Changes committed and pushed successfully"

            # Post success comment
            gh issue comment "${{ github.event.issue.number }}" --body "## ✅ Implementation Complete

**Issue:** #${{ github.event.issue.number }} - ${{ github.event.issue.title }}
**Tech Stack:** \`${{ steps.detect-stack.outputs.stack }}\`

### Changes Made:
$(git diff --stat origin/main...HEAD)"

          else
            echo "No changes to commit"

            # Post no changes comment
            gh issue comment "${{ github.event.issue.number }}" --body "## ℹ️ No Changes Required

**Issue:** #${{ github.event.issue.number }} - ${{ github.event.issue.title }}

The AI agent analyzed the issue but no code changes were necessary."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post comment on PR
        if: github.event_name == 'pull_request' && success()
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "## 🤖 AI Agent Review Complete

**PR:** #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
**Tech Stack:** \`${{ steps.detect-stack.outputs.stack }}\`

### Review Summary:
The AI agent has reviewed this pull request and provided feedback via inline comments.

---
*Reviewed by: enacton-ai*"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unassign AI agent (if issue)
        if: github.event_name == 'issues' && success() && github.event.issue.assignee.login == 'enacton-ai'
        run: |
          echo "Removing AI agent assignment..."
          gh issue edit "${{ github.event.issue.number }}" --remove-assignee "enacton-ai"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
