name: AI Agent Workflow

on:
  issues:
    types: [assigned]
  pull_request:
    types: [review_requested]

# Prevent self-triggering
if: |
  github.actor != 'claude[bot]' && (
    (github.event.issue && github.event.issue.assignee.login == 'super-ai-agent') ||
    (github.event.pull_request && contains(github.event.pull_request.requested_reviewers.*.login, 'super-ai-agent'))
  )

env:
  ANTHROPIC_BASE_URL: ${{ secrets.CUSTOM_ANTHROPIC_BASE_URL }}
  ANTHROPIC_AUTH_TOKEN: ${{ secrets.CUSTOM_ANTHROPIC_TOKEN }}
  CLAUDE_CODE_CONFIG_DIR: ${{ github.workspace }}/.claude-agents

jobs:
  ai-agent-task:
    name: AI Agent Task Handler
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect tech stack
        id: detect-stack
        run: |
          STACK=""

          # Check for Laravel
          if [ -f "composer.json" ]; then
            STACK="$STACK,laravel"
            echo "Detected: Laravel"
          fi

          # Check for Next.js
          if [ -f "next.config.js" ] || [ -f "next.config.mjs" ] || [ -f "next.config.ts" ]; then
            STACK="$STACK,nextjs"
            echo "Detected: Next.js"
          fi

          # Check for React Native
          if [ -d "android" ] || [ -d "ios" ]; then
            STACK="$STACK,reactnative"
            echo "Detected: React Native"
          fi

          # Check for Expo
          if [ -f "app.json" ] && grep -q "expo" app.json 2>/dev/null; then
            STACK="$STACK,expo"
            echo "Detected: Expo"
          fi

          # Remove leading comma and save to output
          STACK="${STACK#,}"
          echo "stack=$STACK" >> $GITHUB_OUTPUT
          echo "Final stack: $STACK"

      - name: Setup Claude Code
        run: |
          # Install Claude Code (if not already installed)
          if ! command -v claude &> /dev/null; then
            echo "Installing Claude Code..."
            npm install -g @anthropic-ai/claude-code
          fi

          # Verify installation
          claude --version

      - name: Configure AI agents
        run: |
          # Create config directory if it doesn't exist
          mkdir -p "$CLAUDE_CODE_CONFIG_DIR"/agents

          # Copy common agents
          echo "Copying common agents..."
          # Agents should be pre-installed in .claude-agents directory

          # Verify agents exist
          ls -la "$CLAUDE_CODE_CONFIG_DIR/agents" || echo "No agents found"

          # List available agents
          echo "Available agents:"
          find "$CLAUDE_CODE_CONFIG_DIR/agents" -name "*.json" -exec basename {} \; | sed 's/.json$//'

      - name: Process Issue
        if: github.event_name == 'issues'
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_AUTHOR="${{ github.event.issue.user.login }}"

          echo "Processing issue #$ISSUE_NUMBER"
          echo "Title: $ISSUE_TITLE"
          echo "Author: $ISSUE_AUTHOR"
          echo "Tech stack: ${{ steps.detect-stack.outputs.stack }}"

          # Run Claude Code agent
          claude agent \
            --config "$CLAUDE_CODE_CONFIG_DIR" \
            --task "Issue #$ISSUE_NUMBER: $ISSUE_TITLE" \
            --context "$ISSUE_BODY" \
            --stack "${{ steps.detect-stack.outputs.stack }}" \
            --output-format pr

      - name: Process Pull Request Review
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_DIFF_URL="${{ github.event.pull_request.diff_url }}"

          echo "Processing PR review for #$PR_NUMBER"
          echo "Title: $PR_TITLE"
          echo "Author: $PR_AUTHOR"
          echo "Tech stack: ${{ steps.detect-stack.outputs.stack }}"

          # Fetch PR diff
          echo "Fetching PR diff..."
          PR_DIFF=$(curl -s -H "Accept: application/vnd.github.v3.diff" \
            "$PR_DIFF_URL")

          # Run Claude Code agent for review
          claude agent \
            --config "$CLAUDE_CODE_CONFIG_DIR" \
            --task "PR Review #$PR_NUMBER: $PR_TITLE" \
            --context "$PR_BODY" \
            --diff "$PR_DIFF" \
            --stack "${{ steps.detect-stack.outputs.stack }}" \
            --agent code-reviewer \
            --output-format review

      - name: Create PR (if implementation changes made)
        if: github.event_name == 'issues'
        run: |
          # Check if Claude created any changes
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes detected, skipping PR creation"
          else
            # Create a new branch for the changes
            BRANCH_NAME="ai-agent/issue-${{ github.event.issue.number }}"
            git config --global user.name "super-ai-agent"
            git config --global user.email "noreply@github.com"
            git checkout -b "$BRANCH_NAME"
            git add .
            git commit -m "AI Agent: Implementation for issue #${{ github.event.issue.number }}"
            git push origin "$BRANCH_NAME"

            # Create PR using GitHub CLI
            gh pr create \
              --base main \
              --head "$BRANCH_NAME" \
              --title "AI Implementation: ${{ github.event.issue.title }}" \
              --body "Automated implementation by AI agent for issue #${{ github.event.issue.number }}

            This PR was created by the super-ai-agent in response to being assigned to issue #${{ github.event.issue.number }}.

            **Original Issue:**
            ${{ github.event.issue.body }}

            **Tech Stack:** ${{ steps.detect-stack.outputs.stack }}

            ---
            *This is an automated PR. Please review all changes before merging.*"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment to issue/PR
        if: always()
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            COMMENT="AI agent has processed this issue.

            **Tech Stack Detected:** ${{ steps.detect-stack.outputs.stack }}
            **Agent Used:** team-lead-orchestrator + tech-specific agents

            ${
              if [ "${{ job.status }}" == "success" ]; then
                echo "Status: ✅ Completed";
                if [ -n "$(git status --porcelain)" ]; then
                  echo "";
                  echo "A PR has been created with the implementation changes.";
                else
                  echo "";
                  echo "No code changes were needed for this issue.";
                fi
              else
                echo "Status: ❌ Failed - Please check the workflow logs for details";
              fi
            }

            ---
            *Processed by super-ai-agent*";

            gh issue comment "${{ github.event.issue.number }}" --body "$COMMENT";
          else
            COMMENT="AI agent review completed.

            **Tech Stack Detected:** ${{ steps.detect-stack.outputs.stack }}
            **Agent Used:** code-reviewer

            ${
              if [ "${{ job.status }}" == "success" ]; then
                echo "Status: ✅ Review Complete";
              else
                echo "Status: ❌ Review Failed";
              fi
            }

            ---
            *Reviewed by super-ai-agent*";

            gh pr comment "${{ github.event.pull_request.number }}" --body "$COMMENT";
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unassign AI agent (if completed)
        if: github.event_name == 'issues' && success()
        run: |
          # Remove assignment from AI agent
          gh issue edit "${{ github.event.issue.number }}" --remove-assignee "super-ai-agent"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
